name: Lint Test 
on:
  push:
    branches: ["main"]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install shellcheck
      run: sudo apt install shellcheck -y
    - name: Check config.sh
      run: shellcheck config.sh
